### ISSUE TITLE
Learn gem cannot interpret gets.chomp

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/looping-break-gets#4]
@matbalez @SophieDeBenedetto @deniznida 

Running `rspec` passes the tests, but running `learn` causes a series of errors meaning the Learn gem never recognizes the local tests as passing and the remote tests will not pass either.

```bash
// ♥ learn
What is the spell that enacts levitation?
/Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:7:in `gets': No such file or directory @ rb_sysopen - --format (Errno::ENOENT)
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:7:in `gets'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:7:in `block in levitation_quiz'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:5:in `loop'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:5:in `levitation_quiz'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/levitation_quiz.rb:13:in `<top (required)>'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/spec/levitation_quiz_spec.rb:2:in `require_relative'
        from /Users/mark/Development/LearnCo/RUBY-000/RUBY-000/06-LOOPING-000/05-LOOPING-BREAK-AND-GETS-000/looping-break-gets-000/spec/levitation_quiz_spec.rb:2:in `<top (required)>'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `<main>'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
/Users/mark/.rvm/gems/ruby-2.2.1/gems/learn-co-1.0.4/lib/learn/rspec/runner.rb:86:in `format_results': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/learn-co-1.0.4/lib/learn/rspec/runner.rb:26:in `run'
        from /Users/mark/.rvm/gems/ruby-2.2.1/gems/learn-co-1.0.4/bin/learn:67:in `<top (required)>'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/learn:23:in `load'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/learn:23:in `<main>'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/mark/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by sammarcus** [comment]
(@matbalez @deniznida @markedwardmurray @SophieDeBenedetto)
the workaround is simply to not call a method that uses `gets.chomp`. 

so, the solution can still be as is, and `learn` will work, as long as the solution does not actually call the sole method they've defined.

I detailed the finding and suggested readme changes to reflect this in https://github.com/learn-co-curriculum/looping-break-gets/issues/6#issuecomment-137272929 :computer:
